export ZSH="/Users/pzl/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(extract)

source ~/.config/zsh-custom/custom.sh

ZSH_DISABLE_COMPFIX=true

source $ZSH/oh-my-zsh.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

if [[ $TERM = dumb ]]; then
  unset zle_bracketed_paste
fi
